language: elixir
elixir:
  - 1.5
go:
  - 1.9
addons:
  postgresql: 9.4 # TODO: try to upgrade this
cache:
  directories:
    - _build
    - deps
git:
  depth: 1
install:
  - mix do local.hex --force, local.rebar --force
  - mix do deps.get, compile, ecto.create, ecto.migrate
script:
  - mix coveralls.travis --umbrella
